language: rust
rust: 1.66
cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench

before_deploy:
  - git config --global credential.helper store
  - echo "https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@mdsol.jfrog.io" > ~/.git-credentials

deploy:
  edge: true # opt in to dpl v2
  provider: cargo
  allow_dirty: true
  on:
    tags: true
