[package]
name = "mauth-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
base64 = "0.13"
hex = "0.4"
lazy-regex = "2"
openssl = "0.10"
regex = { version = "1", default_features = false, features = ["std"] }
sha2 = "0.9"
urlencoding = "2"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
criterion = "0.4"

[[bench]]
name = "benchmark"
harness = false
